version: '3.8'

services:
  db:
    image: postgres:15
    container_name: local_pg
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: craft_vision
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
